insert into tbl_part (part_name) values ('Brake Pads');
insert into tbl_part (part_name) values ('Oil Filter');
insert into tbl_part (part_name) values ('Air Filter');
insert into tbl_part (part_name) values ('Radiator');
insert into tbl_part (part_name) values ('Timing Belt');
insert into tbl_part (part_name) values ('Alternator');
insert into tbl_part (part_name) values ('Spark Plug');
insert into tbl_part (part_name) values ('Battery');
insert into tbl_part (part_name) values ('Headlight');
insert into tbl_part (part_name) values ('Fuel Pump');
insert into tbl_part (part_name) values ('Water Pump');
insert into tbl_part (part_name) values ('Brake Disc');
insert into tbl_part (part_name) values ('Windshield Wiper');
insert into tbl_part (part_name) values ('Exhaust Pipe');
insert into tbl_part (part_name) values ('Tire');